### ISSUE TITLE
Git Missing

### ISSUE THREAD

**Issue by nprail** [beevelop/docker-ionic#24]
I am using Gulp with Microsoft's VS Taco for builds of my Ionic apps. Some of the plugins, specifically `cordova-plugin-vs-taco-support`, are installed via Git. It seems that Git is missing in this image. I don't know if that is intentional or not but without Git, my build is broken.

Here is the error message:
```
Adding support plugin.
[15:41:34] 'build' errored after 40 s
[15:41:34] CordovaError: Failed to fetch plugin https://github.com/Microsoft/cordova-plugin-vs-taco-support.git via git.
Either there is a connection problems, or plugin spec is incorrect:
	Error: "git" command line tool is not installed: make sure it is accessible on your PATH.
    at /root/.taco_home/node_modules/cordova/6.3.1/node_modules/cordova-lib/src/plugman/fetch.js:99:33
    at _rejected (/root/.taco_home/node_modules/cordova/6.3.1/node_modules/q/q.js:797:24)
    at /root/.taco_home/node_modules/cordova/6.3.1/node_modules/q/q.js:823:30
    at Promise.when (/root/.taco_home/node_modules/cordova/6.3.1/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/root/.taco_home/node_modules/cordova/6.3.1/node_modules/q/q.js:741:41)
    at /root/.taco_home/node_modules/cordova/6.3.1/node_modules/q/q.js:557:44
    at flush (/root/.taco_home/node_modules/cordova/6.3.1/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
ERROR: Build failed: exit code 1
```

**Comment by beevelop** [comment]
Yeah, `git` is atm not required anymore and is therefore omitted in the current Dockerfile. I recommend using this image as a base image and adapt it for your use cases.
```Dockerfile
FROM beevelop/ionic:latest
RUN apt-get update && apt-get install -y git && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean
```
