### ISSUE TITLE
Error building app with bitbucket pipelines

### ISSUE THREAD

**Issue by glmagalhaes** [beevelop/docker-ionic#94]
I'm using bitbucket and pipelines to build my app.
Here are the versions from the ionic, npm and node:

```
npm --version
5.3.0

node -v
v8.4.0

ionic info
[INFO] --no-confirm: Looks like a fresh checkout! No ./node_modules directory found. Would you like to install project dependencies? No
[ERROR] Error with ./node_modules/ionic-angular/package.json file: FILE_NOT_FOUND
[ERROR] Error with ./node_modules/@ionic/app-scripts/package.json file: FILE_NOT_FOUND
cli packages: (/opt/node/lib/node_modules)
    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2
global packages:
    Cordova CLI : 7.0.1 
local packages:
    @ionic/app-scripts : not installed
    Cordova Platforms  : none
    Ionic Framework    : not installed
System:
    Android SDK Tools : 25.2.5
    Node              : v8.4.0
    npm               : 5.3.0 
    OS                : Linux 4.12
```

I am having a problem building my app, when it runs the _npm install_ command and returning this error. as far as I can tell python is not installed.

```
npm install
npm WARN deprecated babili@0.0.10: babili has been renamed to babel-minify. Please update to babel-minify
npm WARN deprecated babel-preset-babili@0.0.10: babili has been renamed to babel-minify. Please update to babel-preset-minify
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys

> leveldown@1.5.0 install /opt/atlassian/pipelines/agent/build/node_modules/leveldown
> prebuild --install

prebuild info begin Prebuild version 4.5.0
prebuild info looking for local prebuild @ prebuilds/leveldown-v1.5.0-node-v57-linux-x64.tar.gz
prebuild info looking for cached prebuild @ /root/.npm/_prebuilds/https-github.com-level-leveldown-releases-download-v1.5.0-leveldown-v1.5.0-node-v57-linux-x64.tar.gz
prebuild http request GET https://github.com/level/leveldown/releases/download/v1.5.0/leveldown-v1.5.0-node-v57-linux-x64.tar.gz
prebuild http 404 https://github.com/level/leveldown/releases/download/v1.5.0/leveldown-v1.5.0-node-v57-linux-x64.tar.gz
prebuild WARN install No prebuilt binaries found (target=v8.4.0 arch=x64 platform=linux)
prebuild info install We will now try to compile from source.
prebuild verb starting node-gyp process 
prebuild verb execute node-gyp with `node index.js rebuild --target=v8.4.0 --target_arch=x64` 
prebuild verb command rebuild []
prebuild verb ok 
prebuild verb command clean []
prebuild verb clean removing "build" directory
prebuild verb ok 
prebuild verb command configure []
prebuild verb check python checking for Python executable "python2" in the PATH
prebuild verb `which` failed Error: not found: python2
prebuild verb `which` failed     at getNotFoundError (/opt/atlassian/pipelines/agent/build/node_modules/which/which.js:13:12)
prebuild verb `which` failed     at F (/opt/atlassian/pipelines/agent/build/node_modules/which/which.js:68:19)
prebuild verb `which` failed     at E (/opt/atlassian/pipelines/agent/build/node_modules/which/which.js:80:29)
prebuild verb `which` failed     at /opt/atlassian/pipelines/agent/build/node_modules/which/which.js:89:16
prebuild verb `which` failed     at /opt/atlassian/pipelines/agent/build/node_modules/isexe/index.js:42:5
prebuild verb `which` failed     at /opt/atlassian/pipelines/agent/build/node_modules/isexe/mode.js:8:5
prebuild verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
prebuild verb `which` failed  python2 { Error: not found: python2
prebuild verb `which` failed     at getNotFoundError (/opt/atlassian/pipelines/agent/build/node_modules/which/which.js:13:12)
prebuild verb `which` failed     at F (/opt/atlassian/pipelines/agent/build/node_modules/which/which.js:68:19)
prebuild verb `which` failed     at E (/opt/atlassian/pipelines/agent/build/node_modules/which/which.js:80:29)
prebuild verb `which` failed     at /opt/atlassian/pipelines/agent/build/node_modules/which/which.js:89:16
prebuild verb `which` failed     at /opt/atlassian/pipelines/agent/build/node_modules/isexe/index.js:42:5
prebuild verb `which` failed     at /opt/atlassian/pipelines/agent/build/node_modules/isexe/mode.js:8:5
prebuild verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
prebuild verb check python checking for Python executable "python" in the PATH
prebuild verb `which` failed Error: not found: python
prebuild verb `which` failed     at getNotFoundError (/opt/atlassian/pipelines/agent/build/node_modules/which/which.js:13:12)
prebuild verb `which` failed     at F (/opt/atlassian/pipelines/agent/build/node_modules/which/which.js:68:19)
prebuild verb `which` failed     at E (/opt/atlassian/pipelines/agent/build/node_modules/which/which.js:80:29)
prebuild verb `which` failed     at /opt/atlassian/pipelines/agent/build/node_modules/which/which.js:89:16
prebuild verb `which` failed     at /opt/atlassian/pipelines/agent/build/node_modules/isexe/index.js:42:5
prebuild verb `which` failed     at /opt/atlassian/pipelines/agent/build/node_modules/isexe/mode.js:8:5
prebuild verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
prebuild verb `which` failed  python { Error: not found: python
prebuild verb `which` failed     at getNotFoundError (/opt/atlassian/pipelines/agent/build/node_modules/which/which.js:13:12)
prebuild verb `which` failed     at F (/opt/atlassian/pipelines/agent/build/node_modules/which/which.js:68:19)
prebuild verb `which` failed     at E (/opt/atlassian/pipelines/agent/build/node_modules/which/which.js:80:29)
prebuild verb `which` failed     at /opt/atlassian/pipelines/agent/build/node_modules/which/which.js:89:16
prebuild verb `which` failed     at /opt/atlassian/pipelines/agent/build/node_modules/isexe/index.js:42:5
prebuild verb `which` failed     at /opt/atlassian/pipelines/agent/build/node_modules/isexe/mode.js:8:5
prebuild verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21) code: 'ENOENT' }
prebuild ERR! configure error 
prebuild ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
prebuild ERR! stack     at PythonFinder.failNoPython (/opt/atlassian/pipelines/agent/build/node_modules/node-gyp/lib/configure.js:483:19)
prebuild ERR! stack     at PythonFinder.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/node-gyp/lib/configure.js:397:16)
prebuild ERR! stack     at F (/opt/atlassian/pipelines/agent/build/node_modules/which/which.js:68:16)
prebuild ERR! stack     at E (/opt/atlassian/pipelines/agent/build/node_modules/which/which.js:80:29)
prebuild ERR! stack     at /opt/atlassian/pipelines/agent/build/node_modules/which/which.js:89:16
prebuild ERR! stack     at /opt/atlassian/pipelines/agent/build/node_modules/isexe/index.js:42:5
prebuild ERR! stack     at /opt/atlassian/pipelines/agent/build/node_modules/isexe/mode.js:8:5
prebuild ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
prebuild ERR! not ok 
prebuild ERR! build Error: Can't find Python executable "python", you can set the PYTHON env variable.
prebuild ERR! build     at PythonFinder.failNoPython (/opt/atlassian/pipelines/agent/build/node_modules/node-gyp/lib/configure.js:483:19)
prebuild ERR! build     at PythonFinder.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/node-gyp/lib/configure.js:397:16)
prebuild ERR! build     at F (/opt/atlassian/pipelines/agent/build/node_modules/which/which.js:68:16)
prebuild ERR! build     at E (/opt/atlassian/pipelines/agent/build/node_modules/which/which.js:80:29)
prebuild ERR! build     at /opt/atlassian/pipelines/agent/build/node_modules/which/which.js:89:16
prebuild ERR! build     at /opt/atlassian/pipelines/agent/build/node_modules/isexe/index.js:42:5
prebuild ERR! build     at /opt/atlassian/pipelines/agent/build/node_modules/isexe/mode.js:8:5
prebuild ERR! build     at FSReqWrap.oncomplete (fs.js:152:21)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! leveldown@1.5.0 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the leveldown@1.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-17T02_28_49_801Z-debug.log

```

**Comment by glmagalhaes** [comment]
Hello, I made a branch from your image and added the python executables and the sdk agreements, and it's working fine now, your dockerimage is realy nice.

**Comment by beevelop** [comment]
@glmagalhaes Thanks for the follow up. Would you mind sharing the necessary steps for people struggling with the same issue? Did you install Python via `apt`?

**Comment by glmagalhaes** [comment]
I added a line for the apt-get to install the python packages, here it's:
```
RUN apt-get update && apt-get install -y build-essential python-dev python-pip
```
As setting a docker hub image with GitHub and automated build is quite easy, I will modify mine with the extra tools  and use your as the base image so I can keep the latest ionic version and just focus on my project specifics pre-requisites.

**Comment by beevelop** [comment]
@glmagalhaes Thank you for the sharing your solution.
